### ISSUE TITLE
How to send content which is inside a TXT file?

### ISSUE THREAD

**Issue by MrAlester** [robvanderleek/mudslide#3]
Hi, I'm trying to send a whatsapp text message with the content inside a TXT file but I'm not able to. 

I know this might be a really basic problem but I'm not linux nor npx savvy.

I'm using the command:

cat /tmp/FILE.txt | npx mudslide send me --stdin

**Comment by MrAlester** [comment]
I'll respond myself, maybe it's not the best option but this works.

npx mudslide send me "$(cat FILE.txt)"

**Comment by robvanderleek** [comment]
Hi @MrAlester 

There's indeed no support for reading from stdin (yet, maybe if there's more interest the feature can be added although it can also confuse users since the data would not "stream" to WhatsApp but will be buffered before sending).

Great that you found a workaround 😃  
Do not hesitate to propose new features in an issue, this is however a side project so my time is limited (PRs are welcome also of course).
Also thanks for the sponsor donation, really appreciated.

KR, Rob
