### ISSUE TITLE
Not sending messages on Ubuntu operating system

### ISSUE THREAD

**Issue by weldance** [robvanderleek/mudslide#30]
In windows messages are sent, but in ubuntu - no.

root@host112:/home# /usr/bin/npx mudslide@latest me
Cache folder: /root/.local/share/mudslide
Current user: **********3:8@s.whatsapp.net

root@host112:/home# /usr/bin/npx mudslide@latest send **********2 "321"
…  awaiting  Sending message: "321" to: **********2@s.whatsapp.net
✔  success   Done
…  awaiting  Waiting 3 second(s) for successful delivery...

**Comment by robvanderleek** [comment]
Hi @weldance 

Sorry to hear it's not working for you.

I'm not aware of any Ubuntu-specific issues, I'm using it myself on Ubuntu 20.

Can you try:
```shell
npx mudslide@latest send me "321"
```
to make sure it's not a problem with the phone number.

Otherwise, I suggest to logout, disconnect the app from WhatsApp in your mobile app, and then login again.

**Comment by weldance** [comment]
Спасибо за быстрый ответ.
Попробовал "send me" на виндовс и убунту. В первом случае работает, во втором - нет.
 logout тоже не помог

**Comment by weldance** [comment]
Thanks for the quick response.
Tried "send me" on windows and ubuntu. In the first case it works, in the second it doesn't.
  logout didn't help either

**Comment by lightaffaire** [comment]
datapoint: On fedora 37 running 0.16 'npx mudslide@latest send me "321"' works as expected.

maybe logout, delete the cache, logout mudslide session in WA app and then mudslide login and try again.

**Comment by weldance** [comment]
Unfortunately it didn't help.

**Comment by lrufato** [comment]
More details on this issue. I hope it helps.

user@debian:~$ cat /etc/debian_version 
11.6
user@debian:~$ npx --version
8.19.3
user@debian:~$ npm --version
8.19.3
root@debian:~# npm install -g mudslide

changed 132 packages, and audited 133 packages in 14s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@debian:~# npm update mudslide -g

changed 2 packages, and audited 383 packages in 3s

29 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

user@debian:~$ mudslide send [correctphonenumber] "Test x."
…  awaiting  Sending message: "Test x." to: [correctphonenumber]@s.whatsapp.net
✔  success   Done
…  awaiting  Waiting 3 second(s) for successful delivery...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide

user@debian:~$ npx mudslide@latest send [correctphonenumber] "Test npx."
…  awaiting  Sending message: "Test npx." to: [correctphonenumber]@s.whatsapp.net
✔  success   Done
…  awaiting  Waiting 3 second(s) for successful delivery...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide


The message DOES appear on my WhatsApp Web, but doesn't arrive on both phones and on target WhatsApp Web also. On my WhatsApp Web, there are both grey ticks, meaning they arrive, but since its not viewed on phone, doesn't get the blue ticks. There are no other errors or messages. I already tried log out and log in again. No success.

Thank you very much for yout great work.

**Comment by robvanderleek** [comment]
Hi @lrufato 
There was a bug release (0.17.1), as discussed in [this issue](https://github.com/robvanderleek/mudslide/issues/33).
Can you please give it another try with the latest release?

**Comment by lrufato** [comment]
Working fine on latest release.
Thank you very much for your efforts.
