### ISSUE TITLE
Unexpected token = 

### ISSUE THREAD

**Issue by PappaD** [robvanderleek/mudslide#5]
No matter what I do I get an "Unexpected token =" error message.

```
daniel@instance-1:~$ npx mudslide --help
Unexpected token =
daniel@instance-1:~$ npx mudslide login
Unexpected token =
daniel@instance-1:~$ npx --version
5.8.0
daniel@instance-1:~$ node --version
v10.24.0
```

**Comment by robvanderleek** [comment]
Hi @PappaD

I'm not 100% sure but I think this is due to your version of NodeJS, Mudslide requires NodeJS 16 or higher.

What platform are you on? I've just created new x86 binaries for Linux and Windows: https://github.com/robvanderleek/mudslide/releases/tag/20230130-2

The files are pretty huge but your other alternative would be to upgrade NodeJS.

KR, Rob

**Comment by PappaD** [comment]
Works great on my ubuntu/x86, thank you very much! Is it possible to create a static executable for armv7l / RaspberryPi as well?

**Comment by robvanderleek** [comment]
I've added [a static binary for ARM64](https://github.com/robvanderleek/mudslide/releases/tag/20230130-3) but ARMv7 does not seem so easy to cross-build unfortunately. 

Note that it's also possible to [run Mudslide inside a Docker container](https://github.com/robvanderleek/mudslide#docker), I've updated the README for that.

Let me know if this is of any help 🙂

**Comment by PappaD** [comment]
Thank you very much, great piece of work! I will have a API call from my Raspberry PI to a x86 VM, it solves my problem. The RPI is a embedded appliance that cannot handle docker or node.

**Comment by robvanderleek** [comment]
Nice 😄 
Happy texting!
