### ISSUE TITLE
Since yesterday, upon logging in via QR code, device gets added but immediately removed. Any idea?

### ISSUE THREAD

**Issue by reddyshyam** [robvanderleek/mudslide#86]
I am trying on Linux machine with latest release here.

**Comment by robvanderleek** [comment]
Hi @reddyshyam 

Sorry to hear the application is not working for you. I've just logged out and back in myself, without problems.
This application uses a library (https://github.com/WhiskeySockets/Baileys) to communicate with the WA API, maybe the problem comes from either the library or the WA API.

I'll leave this issue open for a while to see if other users also experience problems.

**Comment by reddyshyam** [comment]
> Hi @reddyshyam
> 
> Sorry to hear the application is not working for you. I've just logged out and back in myself, without problems. This application uses a library (https://github.com/WhiskeySockets/Baileys) to communicate with the WA API, maybe the problem comes from either the library or the WA API.
> 
> I'll leave this issue open for a while to see if other users also experience problems.

Thanks @robvanderleek, appreciate you leaving it open. 🙏

**Comment by reddyshyam** [comment]
Hi @robvanderleek, good day! A quick update. All of the sudden it started working again! May be a glitch with whatsapp. I am closing the ticket as nothing needs to be. 

Thanks again for your time. 🙏

**Comment by robvanderleek** [comment]
Great to hear @reddyshyam 😄 
Thanks for the update.
