### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by SureshVeeraRaghavan** [robvanderleek/mudslide#93]
Hi, I get the following error when I login. Any help please
<img width="948" alt="Screenshot 2024-06-03 at 22 57 19" src="https://github.com/robvanderleek/mudslide/assets/140198587/be5ba98c-7114-4915-b770-fec911979137">

**Comment by SureshVeeraRaghavan** [comment]
Also, I am trying to deploy in a docker container. But unable to connect it with the mobile (Doesn't list chrome in the linked device)

**Comment by robvanderleek** [comment]
Hi @SureshVeeraRaghavan 

Are you running a container build with the [`Dockerfile`](https://github.com/robvanderleek/mudslide/blob/main/Dockerfile) in this repository, or a different docker configuration?

I suspect the error is caused by a missing pseudo-TTY that allows you to interact with the container (the login commands waits for a key-press). Perhaps you can fix this with the `-it` flag, for example: `docker run -it mudslide login`
